version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.35.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.3.0
